### ISSUE TITLE
No sound during calls, unable to connect a call on Firefox (pt. 2)

### ISSUE THREAD

**Issue by Csardelacal** [vector-im/element-web#11453]
I was told to resubmit if the issue we were having with phone calls persisted, we use Modular and since last week have been unable to hear each other after connecting a call.

We received a message yesterday that the issue was no longer there, but it is not solved. Rebuilding the host didn't fix the issue. 

Everything else is here #11366

Again, thanks for looking into the issue.

**Comment by dbkr** [comment]
We found another issue on the modular hosts and fixed it a couple of hours ago - hopefully you've had an email from support to say it should be working now.

**Comment by MadLittleMods** [comment]
Given no response about still reproducing since @dbkr mentioned a fix, I'm going to close this ⏩
