### ISSUE TITLE
Per room notification settings are confusing

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#12012]
<img width="221" alt="Screen Shot 2020-01-22 at 6 22 47 PM" src="https://user-images.githubusercontent.com/5855073/72946300-3422fc80-3d44-11ea-87ec-dcedb3759a3f.png">

I've seen several people now think the speaker icon means it only changes sounds and doesn't change the notification behavior.

**Comment by Biep** [comment]
That is partly because it violates Kent Pitman's two-bit rule - it is one setting trying to do two things.

**Comment by robintown** [comment]
I think this was fixed by the rebranding

**Comment by Biep** [comment]
I am on 1.7.12, and I don't see options to set per-room sound settings and notification settings separately.
I can set *which* sound is played, but not *when* it is played, independently from when a notification is shown.
Ideally, as advanced settings there would be the possibility to set rules, e.g. if a user matching this posts a message matching that in a room matching the other, then this sound is played, and a notification text is (not) shown.  The first matching rule executes, and unless that rule says "keep matching", the search for matching rules stops.
A simpler slider interface can then easily be defined on top of that: setting the slider would simply add an appropriate rule.

**Comment by aaronraimist** [comment]
> I am on 1.7.12, and I don't see options to set per-room sound settings and notification settings separately.

I’m not sure that’s really in the scope of this issue.

> I think this was fixed by the rebranding

Yeah I think it has been improved. I’ll close for now. Can reopen if people are still getting confused.
