### ISSUE TITLE
Unable to leave community error when last one to leave

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#12240]
<img width="792" alt="Screen Shot 2020-02-04 at 4 00 33 PM" src="https://user-images.githubusercontent.com/5855073/73791233-87934280-4767-11ea-96ca-df711735b8cb.png">

Probably related to the community getting deleted when you are the last one to leave https://github.com/matrix-org/synapse/pull/6453

**Comment by Ai-rin** [comment]
It just happened to me even with non-empty community (`+opensuse:matrix.org`) on develop.element.io.

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release

**Comment by worldofgeese** [comment]
What's fixed though? Because I still can't leave a community even with the new Spaces.

**Comment by SimonBrandner** [comment]
Communities are slowly being completely replaced by spaces, so there is no point in fixing a bug in code that will be replaced soon
