### ISSUE TITLE
 Element Electron starts with a black screen when the system starts

### ISSUE THREAD

**Issue by horstvogel** [vector-im/element-web#15486]
Windows 10 pro Electron Element:

Since Element 1.7.8 Electron starts with a black screen when the system starts, 

The problem only happens when you run Element Elektron in full screen, regardless of whether you have just minimized it or you had the application open. If, on the other hand, the element is not executed in full screen, the problem does not occur.

**Comment by jryans** [comment]
Is it a recent regression, or has it always been this way?

**Comment by horstvogel** [comment]
> Is it a recent regression, or has it always been this way?


The problem has existed since Element 1.7.8 Electron.

**Comment by Terpo** [comment]
I can confirm this issue. On startup element is started in full screen, the name of the last conversation is shown but everything else is black. Clicking on the tray icon solves the problem. 

Installed version: 1.7.10

**Comment by jryans** [comment]
@horstvogel Are you also on Windows as well?

**Comment by horstvogel** [comment]
> @horstvogel Are you also on Windows as well?

Yes on Windows 10 pro
Windows 10 pro Electron Element:

Since Element 1.7.8 Electron starts with a black screen when the system starts,

The problem only happens when you run Element Elektron in full screen, regardless of whether you have just minimized it or you had the application open. If, on the other hand, the element is not executed in full screen, the problem does not occur.

**Comment by horstvogel** [comment]
We have this problem about on 80 Windows 10  computer,  whether within the domain or on the RDS Server 2016.

**Comment by jryans** [comment]
Hmm, I wonder if it's specific to certain system configurations...? Could those affected include more details, such as CPU, RAM, GPU, Windows 10 version, etc.?

**Comment by a-mnich** [comment]
I can confirm this issue as already described above.

Element Version: 1.7.15
OS: Microsoft Windows 10 Pro Version 1909 (Build: 18363.1139)
CPU: AMD Ryzen 5 2600X
RAM: 16GB
GPU: AMD Radeon R9 280X
Radeon Software Version 20.9.1

**Comment by jryans** [comment]
As a test, if you edit the Element shortcut to add `--disable-gpu`, does that make the issue go away?

Still not sure of the root cause... There are some similar sounding Electron issues, but they all seem to mention Windows 7. If anyone affected spots an issue in https://github.com/electron/electron/issues that matches what you are experiencing, please mention it here!

**Comment by AluisioASG** [comment]
> As a test, if you edit the Element shortcut to add --disable-gpu, does that make the issue go away?

Running `Riot.exe --hidden --disable-gpu` shows a white screen instead of black, but otherwise it is the same. These colors don't seem to be dependent on the Element theme.

Also, if while that window is open I right-click the tray icon and click "Show/Hide Element", the window then renders correctly.

**Comment by jryans** [comment]
Hmm, thanks for testing. At this point, we are a bit in dark on what's happening here. I am not aware of anything Element-specific in this area, so most likely it's something in Electron that we need to identify.

**Comment by AluisioASG** [comment]
It looks similar to electron/electron#25367, at least in effect, but there isn't much information in there at the moment.

**Comment by Nama** [comment]
The "dead" window also appears (with the last shown content) if I connect or disconnect a display. Also if GPU drivers are restarted.
Unminimizing element from tray fixes it.

**Comment by Tremolo4** [comment]
I can confirm what Nama said. This might be obvious but the bug also occurs when enabling or disabling a screen, e.g. via `WIN` + `P` hotkey.

**Comment by SM0TVI** [comment]
I have a similar issue, XFCE4 + Debian Buster. `element-desktop --hidden` in my Session Startup to have it automagically start when I log in. Broken window (outline of panes, empty), fixed by Showing, then Hiding the element window.

**Comment by c7hm4r** [comment]
I had the same problem since a long time ago under {Fedora 33 and 34} with Wayland. Even when not maximized when closed, Element did start with a black, screen-filling but not properly maximized window. Clicking on the tray icon made Element show up normally.

**Workaround**: I signed out from Element, removed my profile folder `~/.config/Element` (probably a folder in `%HOME%\AppData` under Windows), launched Element and signed in again. Since then, I did not experience this issue anymore.

So I guess that the problem has to do with some weird state inside the profile folder. I can provide more info, but not publicly.

The tag `Z-Platform-Specific` seems to be inappropriate.

**Comment by turt2live** [comment]
Is anyone still seeing this? Are your graphics drivers up to date/is your card fully functional?

**Comment by maranov** [comment]
@turt2live, it kept happening to me consistently, but the issue seems to be gone for about a year now.

**Comment by turt2live** [comment]
I'm going to declare it fixed through magic then, thanks! If folks run into this again, please open a new issue.

**Comment by Tremolo4** [comment]
The issue is fixed for me on Windows. I think it still happens on one of my Linux machines, but I will only get a chance to test that in a few days.

**Comment by SM0TVI** [comment]
Ditto here, a year or little longer without issues. Maybe have this issue in the back of the head if something with similar symptoms rears its ugly head in the future (always an problem with automagically solved issues).

**Comment by Tremolo4** [comment]
> The issue is fixed for me on Windows. I think it still happens on one of my Linux machines, but I will only get a chance to test that in a few days.

Yep, still happens on my Ubuntu 20.04 machine. The window is blank white, the window title refers to a recently opened conversation. Clicking on the tray icon and selecting "Show/Hide" makes the window work correctly.
Since this is just a minor inconvenience, I'm unwilling at the moment to reset my profile [as was mentioned above](https://github.com/vector-im/element-web/issues/15486#issuecomment-841802579).

**Comment by eiery** [comment]
I have gotten this issue a few times on multiple Ubuntu 20.04 machines; it has not been fixed. Resetting the profile does work and sometimes it disappears after a reboot, but it's very inconsistent.

**Comment by floviolleau** [comment]
Hi, 

I'm facing the same issue on an Ubuntu Budgie 22.10.

Clicking on the tray icon and selecting "Show/Hide" makes the window work correctly but now I have no more tray icon..

Any clues ?

**Comment by olfMombach** [comment]
This issue is still happening for me on Linux Mint 22.1
Element version: 1.12.24
Crypto version: Rust SDK 0.18.0 (6fe03c1), Vodozemac 0.10.0

Especially painful since it happens when set to "Open Element when you log in to your computer" -> "Minimised", so it just pops up an empty but space-filling window on startup.
