### ISSUE TITLE
Community menu doesn't work

### ISSUE THREAD

**Issue by iursino** [vector-im/element-web#16183]
### Description

When you select a community in the left hand community menu in element-web it clears the people and rooms instead of showing the ones in the community. (works on mobile).

### Steps to reproduce

- Make a community that has users and chats in it.
- Click on community so that it highlights in the leftmost division of the app
- People and Rooms dropdowns become empty.

![image](https://user-images.githubusercontent.com/55510266/104853397-63b40880-58b5-11eb-91c9-2fe4795fac6c.png)

Shouldn't

### Version information

- **Platform**: Browser

- **Browser**: Brave Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)
- **OS**: Windows
- **URL**: app.element.io

- **Platform**: Desktop

- **OS**: Windows
- **Version**:  1.7.16

**Comment by SimonBrandner** [comment]
Whatever is going on here it will be fixed by [Spaces](https://github.com/vector-im/element-web/issues/15930) - the new version of communities.

**Comment by iursino** [comment]
It got fixed by the latest update.

**Comment by SimonBrandner** [comment]
@iursino Then you can close this

**Comment by ad-si** [comment]
In the Desktop app (version 1.7.24) this bug still exists. Isn't the Deskop app based on this code?

**Comment by SimonBrandner** [comment]
@ad-si, it is. Normally, I'd tell you to open a new issue but it is unlikely this will get fixed because Spaces are going to replace Communities soonish

**Comment by ad-si** [comment]
Ok, I see. Then I will wait, as it's not critical…
