### ISSUE TITLE
Some members of a space are missing in the people section of the room-list

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17291]
![Screenshot_20210513_190305](https://user-images.githubusercontent.com/25768714/118159913-ebea8a80-b41d-11eb-95bf-72accc1008f1.png)

As you can see in the image, Jonathan is part of the space but they're not shown in the room-list. The image was taken a few seconds after they joined but I've also seen this in other situations. I'll try to keep my eyes on this from now on.

Logs: ~~Will send~~ Sent

**Comment by t3chguy** [comment]
Sounds your dm room map might be out of whack, can you check if m.direct has the room correctly listed along with their MXID?

**Comment by SimonBrandner** [comment]
```json
"@jboi:jboi.nl": [
      "!AlFAyWNjLTRtfjIwmH:jboi.nl"
    ],
```

seems correct. It took a while but now they are there. I'd like to say that there is just some delay but after I restart Element, similar things happen:

![Screenshot_20210513_191514](https://user-images.githubusercontent.com/25768714/118161338-bd6daf00-b41f-11eb-80ce-b1c6c73da75b.png)
![Screenshot_20210513_191523](https://user-images.githubusercontent.com/25768714/118161343-be064580-b41f-11eb-9bbe-56e229eb6f02.png)

**Comment by t3chguy** [comment]
The delay when restarting Element is expected, this is caused by Lazy Loading

**Comment by SimonBrandner** [comment]
How long should the delay be? It's been three minutes and still nothing..

**Comment by t3chguy** [comment]
not that long, unless your HS is particularly unhappy

**Comment by SimonBrandner** [comment]
This has been happening for quite a while and envs.net seems to be fine

**Comment by williamkray** [comment]
I seem to have this issue as well. selecting a space shows only three DMs, despite having _many_ DMs with other members of the space. Happy to send logs along to this issue as well if it will help.

**Comment by novocaine** [comment]
@SimonBrandner have you seen this issue recently?

**Comment by SimonBrandner** [comment]
> @SimonBrandner have you seen this issue recently?

I've been testing this ~14 days ago and it still was there, will give it another check soon

**Comment by SimonBrandner** [comment]
Still here, sorry :(

**Comment by SimonBrandner** [comment]
In https://github.com/vector-im/element-web/issues/18700 T reports that this can also happen to rooms, though I haven't seen that myself

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6713

**Comment by Thatoo** [comment]
pbm isn't solved so far for me v1.8.5 of element-destop. I tried also an "empty cache and restart" from settings...
