### ISSUE TITLE
Community invite for community that is "not found" can't be dismissed or rejected

### ISSUE THREAD

**Issue by amalon** [vector-im/element-web#17368]
### Description

Somebody invited me to a community, And apparently then deleted the community. As a result I have an invite in element, but when i click on it I see a blank page to the right of the room list with only the text:
"Community +<community-name>:matrix.org not found"

There doesn't appear to be a way to delete/dismiss/reject the invite.

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.24

**Comment by t3chguy** [comment]
Communities are deprecated in favour of Spaces in Beta now

**Comment by amalon** [comment]
> Communities are deprecated in favour of Spaces in Beta now

All the more reason not to want a stale invite stuck in my element forever? :-)

**Comment by t3chguy** [comment]
Resolved by Spaces. The community invite not being rejectable is a Synapse issue, but once Spaces land or when you opt-in to the Beta you won't be presented with Community invites anyhow.

**Comment by amalon** [comment]
@t3chguy 
> Resolved by Spaces. The community invite not being rejectable is a Synapse issue, but once Spaces land or when you opt-in to the Beta you won't be presented with Community invites anyhow.

I have element-desktop 1.7.29 (with labs/spaces enabled) and am running synapse 1.34.0-3 (both archlinux latest), and am still getting the broken invite showing up on the sidebar no matter what space is selected.

I have this at the end of my homeserver.yaml:
``` yaml
experimental_features:
  spaces_enabled: true
```

Is that expected and I just need to wait for updates?

**Comment by t3chguy** [comment]
Well I guess I mis-spoke, will make a PR to hide community invites for when Spaces is enabled shortly

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/6244 will deal with that
