### ISSUE TITLE
Persons missing in space

### ISSUE THREAD

**Issue by rgpublic** [vector-im/element-web#19020]
### Steps to reproduce

I'm unsure if anyone else filed this already but I couldn't find anything... For a while now, it seems that many persons are missing from my sidebar in a space. I can chat to them via the plus button but then the home tab is selected. I see the person is member of the space, though. On the home button, all persons seem to appear.

### What did you expect?
All my coworkers should be listed on the sidebar as they are member of the space. At the very least, I should be able to manually add them to the list.

### What happened?
The tab bar just switches to the home tab if I try to add additional users.

### Operating system

Manjaro Linux

### How did you install the app?

AUR

### Have you submitted a rageshake?

No

**Comment by kittykat** [comment]
I have seen this before, although can't reproduce at the moment.

@rgpublic We need to know what app version you are using, you can find it in Settings -> Help & About or from your AUR package/helper

**Comment by t3chguy** [comment]
This is likely an issue with your account_data `m.direct` event not properly knowing which DM is for which members, this will be resolved as part of an external project called Canonical DMs which tidies up the DMs from heuristics to explicit facts.

**Comment by rgpublic** [comment]
@kittykat: I have this problem at home (Manjaro) and here at the office (Kubuntu). Interestingly, here at the office there are some other persons in the list but also not all persons. I'm on 1.8.2 here at the office (just checked via Help & About) and I'm pretty sure also at home.

@t3chguy: Thanks for the information. Good to know this is on the radar. Other coworkers already were quite confused about this. But it's not a big issue of course if you know what's going on.

Thank you all for the great work!

**Comment by robintown** [comment]
@t3chguy Is this not a duplicate of https://github.com/vector-im/element-web/issues/17291?

**Comment by t3chguy** [comment]
Not quite, that one was confirmed to not be an `m.direct` issue - proposing that this one probably is

**Comment by robintown** [comment]
@rgpublic Could you please update to 1.8.5 when you get the chance and see whether you can still reproduce the issue? I just strongly suspect this is https://github.com/vector-im/element-web/issues/17291, which is fixed in 1.8.5.

**Comment by rgpublic** [comment]
Yes, I just upgraded to 1.8.5 and all missing persons magically appeared. So, I'd say this is solved.

**Comment by Thatoo** [comment]
> Not quite, that one was confirmed to not be an `m.direct` issue - proposing that this one probably is

@t3chguy how did you solve it? I'm asking because updating to v 1.8.5 didn't solve the problem for me.
It works as expected in Android but not on my desktop...
