### ISSUE TITLE
Alt text for user avatars is unnecessary

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-web#20550]
### Your use case

While element is loading user avatars, it shows this:
![image](https://user-images.githubusercontent.com/25297359/149495697-ea80060c-f511-4c33-9f4b-6fa0bdaee4cb.png)

Can we just show something like this, like for users that have no avatar at all:
![image](https://user-images.githubusercontent.com/25297359/149495870-f923489b-33f1-4c94-9e9f-ac6ab24d29b8.png)

**Comment by t3chguy** [comment]
I can't say I've ever seen this, nor a browser showing alt text during the image resource loading, do you have some specific configuration/extensions which make this happen?

**Comment by timokoesters** [comment]
I'm using firefox 94.0. I don't think it's an extension (it happens too if I disable my adblocker)

**Comment by f0x52** [comment]
related: it's also not very useful to have screen readers make every message group read "Avatar", might be better to skip that alt-text altogether?

**Comment by CyberTailor** [comment]
> related: it's also not very useful to have screen readers make every message group read "Avatar", might be better to skip that alt-text altogether?

What if alt text was username? Because clicking on avatar opens user's profile.

**Comment by f0x52** [comment]
the username is already a text element for every message group, so that would still be kinda redundant

**Comment by timokoesters** [comment]
This still reliably happens to me when I scroll up.

**Comment by robintown** [comment]
This has been fixed by the new avatar component

**Comment by psrpinto** [comment]
@robintown I just tested this on `develop` and the issue is still present, screen reader still says "Jane Doe profile picture".

Maybe the new avatar component hasn't been released?

**Comment by psrpinto** [comment]
That makes sense, thanks for the clarification.
