### ISSUE TITLE
Can't see poll results after voting from android

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21368]
### Steps to reproduce

1. Create poll using schildi android beta 1.4.2.sc49.test10
2. answer poll using the same
3. view on E desktop

#### What did you expect?
see all votes, including my own: e.g. on android it says there are 4 votes, and the results are shown because I voted

#### What happened instead?
can only see others votes: per the same example, desktop only says there were 3 votes, despite my own vote showing up on the timeline when enabling hidden events. the results are not shown, since it thinks i didn't vote yet

A diff of my own and someone else's event sources shows nothing significant.

### Operating system

arch

### Application version

Element Nightly version: 2022030801 Olm version: 3.2.8

### How did you install the app?

aur nightly

### Homeserver

1.53

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
Looking at the same poll from E desktop W10 Element version: 1.10.6 Olm version: 3.2.8, there are only "2 votes cast" instead of 5 on android. As before it does not show my own vote.

**Comment by andybalaam** [comment]
@HarHarLinks please can you post the full event source of the events that are not showing up?

**Comment by HarHarLinks** [comment]
The poll in question is now shown correctly on arch Element Nightly version: 2022031201 Olm version: 3.2.8.
Can't repro successfully at this time (note: android has also updated in the meantime).

src of my own event that formerly didn't show up:
```json
{
    "decrypted": {
        "content": {
            "body": "b6b52c67-6421-462f-bffe-7cac286e4d92",
            "org.matrix.msc3381.poll.response": {
                "answers": [
                    "b6b52c67-6421-462f-bffe-7cac286e4d92"
                ]
            },
            "m.relates_to": {
                "event_id": "$VYXKJqQ6KeP8y2Gowrtq7cmQgkugeoTmLQ4skgpf6_I",
                "rel_type": "m.reference"
            }
        },
        "origin_server_ts": 1646846469679,
        "room_id": "!myroom",
        "sender": "@me",
        "type": "org.matrix.msc3381.poll.response",
        "unsigned": {
            "age": 416900124
        },
        "event_id": "$NwHpC8X3hjYSeifD8l6rY2yDgGuQTs_ulw4dyDKir3U",
        "user_id": "@me",
        "age": 416900124
    },
    "encrypted": {
        "content": {
            "algorithm": "m.megolm.v1.aes-sha2",
            "ciphertext": "-",
            "device_id": "???",
            "m.relates_to": {
                "event_id": "$VYXKJqQ6KeP8y2Gowrtq7cmQgkugeoTmLQ4skgpf6_I",
                "rel_type": "m.reference"
            },
            "sender_key": "-",
            "session_id": "-"
        },
        "origin_server_ts": 1646846469679,
        "room_id": "!myroom",
        "sender": "@me",
        "type": "m.room.encrypted",
        "unsigned": {
            "age": 416900124
        },
        "event_id": "$NwHpC8X3hjYSeifD8l6rY2yDgGuQTs_ulw4dyDKir3U",
        "user_id": "@me",
        "age": 416900124
    }
}
```

the poll being `Event ID: $VYXKJqQ6KeP8y2Gowrtq7cmQgkugeoTmLQ4skgpf6_I` with possible answers `"id": "b6b52c67-6421-462f-bffe-7cac286e4d92"` and `"id": "ddf00840-187a-4d1e-9983-12ac3043f0e2"`.

**Comment by andybalaam** [comment]
OK, it sounds like this is fixed - please don't hesitate to re-open, or create a new issue if you see this again.

Thank you!

**Comment by waclaw66** [comment]
Still a problem in Element Web 1.10.11. Encrypted room, 4 members, poll with 3 answers created by creator of that room, 3 votes so far, Element Android shows them, but Element Web shows no votes. Once voted from Web, counter increased to 1, the other votes still not visible. Vote changed from Element Android, vote dissapers on Web. Needs more testing, bugs are on both sides Web-Android.

**Comment by G2G2G2G** [comment]
we have this too at my office
element-web is displaying all of them fine
element-android is displaying some votes, some not. Some of those votes are from other phones, some are from desktops

if the users re-vote again on the same item (switch vote to a different one and back) while the phone is open on that page, it'll usually update to show the vote correctly

Does the server not save the results to send to the clients? Is it client sending the results to other clients?

**Comment by kerryarchibald** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9877
(Polls now use /relations API to fetch all votes)
