### ISSUE TITLE
Electron window crashes about once a day (presumed OOM)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22690]
### Steps to reproduce

Unclear.

Steps I took:
1. Use Nightly for ~1 day (between upgrades)
2. Open Spotlight search
3. Type 2 characters
4. Crash

#### What did you expect?

The app to work :p

#### What happened instead?

White screen of welcome.

### Operating system

Windows 10

### Application version

Nightly (2022-06-28)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by turt2live** [comment]
happened again, this time without me being present. Was working fine, stepped away for a few minutes, crashed by the time I returned.

**Comment by turt2live** [comment]
... and again, this time when switching rooms. This is now indicative of a memory leak.

**Comment by turt2live** [comment]
This is likely fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9273

**Comment by turt2live** [comment]
Declaring fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9273 - haven't seen an OOM since.

**Comment by weeman1337** [comment]
I can confirm that there have been no crashes for a while :+1:

**Comment by FilBot3** [comment]
Well, I'm still getting it on Pop!_OS 22.04 LTS.

```bash
..ownloads/nextcloud-container❯ flatpak uninstall --delete-data im.riot.Riot 


        ID                Branch      Op
 1. [-] im.riot.Riot      stable      r

Uninstall complete.
Delete data for im.riot.Riot? [y/n]: y
..ownloads/nextcloud-container❯ flatpak --user install im.riot.Riot
Looking for matches…
Remotes found with refs similar to ‘im.riot.Riot’:

   1) ‘flathub’ (user)
   2) ‘flathub-beta’ (user)

Which do you want to use (0 to abort)? [0-2]: 1

im.riot.Riot permissions:
    ipc      network      pulseaudio      wayland      x11     devices     file access [1]     dbus access [2]     bus ownership [3]

    [1] xdg-run/keyring, xdg-run/pipewire-0
    [2] org.freedesktop.Notifications, org.freedesktop.ScreenSaver, org.freedesktop.portal.Fcitx, org.kde.StatusNotifierWatcher
    [3] org.kde.*


        ID                   Branch         Op        Remote         Download
 1. [✓] im.riot.Riot         stable         i         flathub        124.1 MB / 119.4 MB

Installation complete.
..ownloads/nextcloud-container❯ flatpak run im.riot.Riot 
[3:0313/163812.289457:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
/home/filbot/.var/app/im.riot.Riot/config/Element exists: no
/home/filbot/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 16:38:12.975: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:38:12.976: Failed to load module "canberra-gtk-module"
[3:0313/163812.999529:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0313/163812.999569:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
Changing application language to en-us,en,en,en
Fetching translation json for locale: en-us
Fetching translation json for locale: en
Fetching translation json for locale: en
Fetching translation json for locale: en
Resetting the UI components after locale change
[52:0313/163923.801028:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
/app/bin/element: line 21:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

I remember it being something about the "search" functionality causing issues. that was a year ago and I've reinstalled since then.

**Comment by sadsfae** [comment]
Fedora 36 / Flatpak user here: I was able to trigger this by resetting the index store under _Security and Privacy --> Message Search_

I then began to see:

```
[2240709.640155] traps: ThreadPoolForeg[1255507] trap int3 ip:5584d0f44224 sp:7f12b09fa7e0 error:0 in element-desktop[5584cd6be000+785e000]
[2241160.706631] traps: element-desktop[1257087] trap int3 ip:564690b82d3f sp:7ffff1749870 error:0 in element-desktop[56468d2fd000+785e000]
```

The reason I messed with it was search wasn't working for encrypted channels, after resetting it it started to grow in size and appeared to be working then crashes began.

I re-installed Element Desktop via:

```
flatpak uninstall --delete-data im.riot.Riot
flatpak install im.riot.Riot
```

After this I logged back and crashes persisted.  After launching it a few more times I noticed the Message / Index store area now displays:

```
Message search initialization failed
Advanced
Error opening the database: IndexError(IOError(IOError { path: None, err: Custom { kind: Other, error: "Invalid MAC" } }))
```

**So far so good (with message index database mad about something).**  I'll use it throughout the day and see if this somehow circumvents or is/was related to the crashes.

It appears for me the crashes are related to a functioning encrypted index message store, at least with the official latest flatpak.

**Comment by kambiz-aghaiepour** [comment]
I've also been experiencing this.  I noticed in my riot/element client (also on Fedora 36 installed via flatpak running the latest):
```
Element version: 1.11.25
Olm version: 3.2.12
```

In one of my rooms, messages from another user were just reading as:

```
Unable to decrypt message
```

for all messages from that user.  That was coupled with the fact that under Security & Privacy -> Message Search, I had what @sadsfae saw which was:

```
Message search initialization failed
Advanced
Error opening the database: IndexError(IOError(IOError { path: None, err: Custom { kind: Other, error: "Invalid MAC" } }))
```

Thinking this is a problem, I pressed reset, and now my Element crashes continuously, though seems to work fine if I use a chrome browser window.  This does seem to be related to the message search, and since the browser based element window keeps working, and Security & Privacy -> Message search in the chrome browser reads:

```
Message search
Element can't securely cache encrypted messages locally while running in a web browser. Use [Element Desktop](https://element.io/get-started) for encrypted messages to appear in search results.
```

It does seem to support search being part of the problem.  I was able to keep the Element/riot native client from crashing, by launching it, and going into the setting mentioned and disabling it before the client crashed.  And now it's up and running.

**Comment by wlinna** [comment]
Something similar happens on my computer (Pop!_OS 22.04, Flatpak) on multiple versions of Element. After logging in / verifying, Element will crash very quickly. I had to try multiple times before I had enough time to disable search. Now Element has been running for hours without crashing.
