### ISSUE TITLE
Epic: Fix stuck notifications

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24392]

**Comment by Johennes** [comment]
Descoping https://github.com/vector-im/element-web/issues/24373 as this doesn't have the same level of severity as the other issues.

**Comment by 8227846265** [comment]
I hope this gets fixed soon. :(

My stuck notification is around 20+ now for the past few weeks, which pops out every time my computer reboots.

**Comment by Johennes** [comment]
As mentioned in the issue description, the remaining bugs will require a spec change. We're currently in the process of drafting the MSC but it'll, unfortunately, be more involved than just a simple client-side bug fix.

**Comment by jplatte** [comment]
I don't think that is true. If you look at the comments in #24595, you will find some from rooms where threads were never used and IME clearing cache often fixes these issues.

**Comment by Johennes** [comment]
We're focusing on the most prominent problems first which are in the interplay of threads and other relations. There may be further issues beyond that.

**Comment by AlBundy33** [comment]
I had the same issue in some rooms.
Because I don't participate that much in this rooms I tried to write a test-message and it seems that the stuck notifications are gone.

**Comment by 8227846265** [comment]
Hopefully we're closer to the release that will fix this bug.

I'm now 33 stuck notifications :(
![image](https://user-images.githubusercontent.com/66582769/231960438-edc4c530-3a27-4fa7-895b-5257ae2fa86a.png)

**Comment by 8227846265** [comment]
Hello, are we close to the release that will fix this bug? Hopefully, it will be up soon :(

It's hard to explain to people I recommended Element for their personal or work use why this bug has been ongoing for the past 2 months. 

Perhaps a few of them of remains at this point in case they encountered this bug and experienced it on prolonged period.

**Comment by Johennes** [comment]
@8227846265 the threads-related stuck notification issues are blocking on https://github.com/matrix-org/matrix-spec-proposals/pull/3981.

**Comment by 8227846265** [comment]
@Johennes noted, thank you. I'll check it out.

**Comment by Johennes** [comment]
We've completed initial implementations for it last week and are now starting to prepare for testing it. Unfortunately, it'll still take some more time to get this landed due to the nature of the spec process.

**Comment by 8227846265** [comment]
I understand. Looking forward for the fix 👍

**Comment by leonardehrenfried** [comment]
@Johennes Thanks for this explanation. If there is an environment where a regular user could help test it, I'd love to hear about it.

**Comment by Johennes** [comment]
Thanks @leonardehrenfried. We will most likely be enabling it on beta.matrix.org as to not impact regular users but you can sign-up for a separate account there if you want to help testing.

**Comment by alexander-potemkin** [comment]
@Johennes , thanks for the explanation indeed! How soon it could be expected to land to the self hosted solutions?

**Comment by Johennes** [comment]
I'd expect the initial PRs (https://github.com/matrix-org/synapse/pull/15315 & https://github.com/matrix-org/matrix-js-sdk/pull/3248) to land this week.

**Comment by 8227846265** [comment]
Sigh, I thought the latest stable update's https://github.com/matrix-org/matrix-react-sdk/pull/10730 will somewhat solve the stuck notification issue until this fix is released. It didn't.

No matter how many times I click `Mark as Read` a single reboot will just bring the stuck notification back.

Hopefully, this will release soon. I got 8+ stuck notifications on 3 Spaces.

**Comment by Johennes** [comment]
@8227846265 we have one more fix in the making that doesn't depend on the MSC (https://github.com/vector-im/element-web/issues/25196) and should land soon. If that one doesn't help your case, we'd be interested to hear more details about your particular error scenario.

**Comment by 8227846265** [comment]
@Johennes Sure, I'll test out the fix once it's available and send feedback here if I encounter any issues.

**Comment by t3chguy** [comment]
@neilisfragile sent logs in https://github.com/matrix-org/element-web-rageshakes/issues/21575

**Comment by kittykat** [comment]
If it helps figure out what introduced it, I'm not seeing the issue that I've got on app.element.io

**Comment by andybalaam** [comment]
Gack, github tasklist overwrote the whole issue with an old version. I tried to fix it - sorry if I did it wrong

**Comment by alexander-potemkin** [comment]
I see that things are addressed, but at the same time, it takes time to fix things. Is there probably any workaround? Like, I don't know - restart the server with some cache cleanup, etc.?

It indeed makes use of the app quite complicated...

**Comment by AlBundy33** [comment]
You can try https://github.com/vector-im/element-web/issues/24392#issuecomment-1491387088

**Comment by alexander-potemkin** [comment]
> You can try [#24392 (comment)](https://github.com/vector-im/element-web/issues/24392#issuecomment-1491387088)

@AlBundy33 , thank you!

Do you mean?
> I had the same issue in some rooms.
> Because I don't participate that much in this rooms I tried to write a test-message and it seems that the stuck notifications are gone.

If so - does the test message is some special service command? If not, I believe I'm participating in the channels, I can see the threads with messages that are presumably not read, but they are kind of 'unread forever'...

**Comment by AlBundy33** [comment]
yes - I've tried different things.
- logout and login
- clear caches (somewhere in settings)
- mark rooms as read
- scroll through the room to "read all (at least some of the last) messages"
but after the next start of the client the same rooms are unread again (even without new messages).

Then I wrote a message into the affected rooms (I think I did some of the steps above before).
After that the rooms where fixed even after a restart of the client.

then I simply did some

**Comment by Valodim** [comment]
Can someone give an update on what the expected state of affairs is on this? Should we expect things to be fixed? Or is there still ongoing work?

Since this is a meta-issue on a problem that's been ongoing for many months, it would be nice to get *some* updates on this every once in a while.

**Comment by andybalaam** [comment]
Hi @Valodim, thanks for the message - I can see lots of people are still affected by this. You can follow our progress somewhat by looking at the tasks closed in the task lists above, but the situation is:

* Many bugs have been found and fixed
* Several harder problems required spec updates and server-side fixes, and we are working on those, but they take longer.
* Several bugs still remain, and we are continuing to work on them.

Rest assured that we are still aware this is an ongoing problem, and we continue to work on it. The reason it's been so long is that our early work uncovered tons of new issues that were masked by the fact that we had a bug incorrectly marking threads as read when they were not.

**Comment by andybalaam** [comment]
I'd also like to say again how sorry we are for the pain this is causing to lots of people. We are all heavy users of Element Web, and have been feeling the pain too. We are determined to fix this problem properly, not patch over it with kinda-working hacks.

**Comment by Valodim** [comment]
Thanks for your response Andy. I understand it's a tough issue and we all very much appreciate your work on this :+1:

> You can follow our progress somewhat by looking at the tasks closed in the task lists above

I understand where you're coming from, but this is actually pretty difficult from an outside perspective. There are lots of issues related to this problem, some of them very general, some of them with large discussions, some with just technical jargon focused on fixing the technical issue at hand, and so on. Extracting a broader overview on the state of the problem from that data is not easy to do.

I regularly find myself in a situation where I'm acting as an ambassador of sorts for the ecosystem (as I'm sure many other admins of their local communities do). This particular issue has been a real hotspot on that front, that's why it would be tremendously helpful in order to give confident answers to users, if there was an update on this the high level issue once in a while.

Hopefully this doesn't come off as too pushy. We all care about Matrix and want it to succeed  :v:

**Comment by andybalaam** [comment]
> Extracting a broader overview on the state of the problem from that data is not easy to do.

Absolutely. I can't wait for the day when we can say "it's fixed!" Until then it's a bit of a whack-a-mole situation: when we fix something we try to be sure that we are definitely improving the behaviour, and we try to be super-sure we're not breaking any other fixes, but we don't usually know which symptoms will go away after a specific fix, so it's tricky to give proper updates, but we'll try to do better in future, by posting updates here.
 
> I regularly find myself in a situation where I'm acting as an ambassador of sorts for the ecosystem (as I'm sure many other admins of their local communities do). This particular issue has been a real hotspot on that front, that's why it would be tremendously helpful in order to give confident answers to users, if there was an update on this the high level issue once in a while.

Thank you for your work! I am personally really aware of how painful this has been, and that can't have made it easy for you as an advocate.
 
> Hopefully this doesn't come off as too pushy. We all care about Matrix and want it to succeed v

Not at all. Thank you for the feedback.

**Comment by johanricher** [comment]
> Hopefully this doesn't come off as too pushy. We all care about Matrix and want it to succeed :v: 

Same here, and as most people who have been closely following the issues related to threads these last few months (since they have been out of beta and sometimes even before), I want to continue advocating for Matrix/Element and support all the good people working on it.

Considering that these issues are various, complex, unpredictable and _should_ take a lot of time and effort until threads work "as expected" (which is in itself quite a challenge, given how user expectations can be subjective!), wouldn't it be possible to roll them back (disable Threads by default and/or make them a Labs feature again)? I'm thinking it would also release at least some of the pressure to take the time needed to work on this with proper conditions.

**Comment by Johennes** [comment]
Thanks everyone for bearing with us. We are aware of the problems and, in fact, we do suffer ourselves as we're all using Element for work. We're working on resolving this situation with the resources currently available to us. I acknowledge that we haven't always been good at communicating status externally. We will try to improve this going forward. I've updated the issue description above with a summary of the currently known problems and a high-level action plan for our next steps.

**Comment by Johennes** [comment]
@ExplodingWaffle we can't currently reliably mark threads as read due to the technical issues explained in the issue description. While I empathize with some of your thoughts, this is also not the right place to discuss thread-related product changes. We're purely concerned with making notifications not stick after you've read them here.

**Comment by 9uenther** [comment]
We've also had the problem with persistent or recurring notifications for awhile. 
What I noticed is that it only affects edited messages with mentions. Maybe it helps.

**Comment by mutantcornholio** [comment]
Can we at least ask for a button "mark every single message as read across all spaces"?  
Even restarting Element doesn't help anymore, and I can't understand which channels do have new messages and which aren't.

**Comment by t3chguy** [comment]
> Can we at least ask for a button "mark every single message as read across all spaces"?

![image](https://github.com/vector-im/element-web/assets/2403652/00e3a12a-2dab-4c45-a230-fd580bf0e54d)

Already in Settings > Notifications

**Comment by mutantcornholio** [comment]
> Already in Settings > Notifications

Hmm, not for me (using 1.11.35, electron version)
![Screen Shot 2023-07-10 at 12 26 40](https://github.com/vector-im/element-web/assets/588262/af183410-630f-45ad-bf90-2d15d4e3ac41)

**Comment by andybalaam** [comment]
I updated the summary at the top of this issue to reflect our current understanding. This week I will be pushing https://github.com/matrix-org/matrix-spec-proposals/pull/4033 and trying to debug some of the known issues to identify their causes.

**Comment by mutantcornholio** [comment]
The thing is, I'm constantly trying to restart the app **in order** to get stuck notifications to disappear (helps in some cases). 

Currently, the button does not mark some messages as read at all. 
If it would mark all of the messages as read, but some of that would come back after restart, I'd consider that "less broken".

**Comment by t3chguy** [comment]
Contributions welcome, but I doubt there'll be any bandwidth from the team to work on anything other than the final solution

**Comment by bhearsum** [comment]
> > @mutantcornholio then the app isn't seeing that sending manual read receipts would fix the issue.
> 
> Maybe it should also remove every black circle, just from UI? Otherwise, it's more like "resend read receipts", not "mark all as read"...

At the risk of piling on, this highlights one of the big disconnects for me. As a user viewing my local UI, it doesn't matter to me whether or not read receipts have been send, received, or whatever. Notifications are an _entirely_ local experience. When I have seen the messages, I consider them read regardless of _any_ network requests. I think this will always be a frustrating experience (and prone to bugs like this) when the UI that tells me whether or not I have read a message is tied to state or network requests that are entirely unrelated to that.

**Comment by samim23** [comment]
Sending all the dev working on resolving this issue lots of good luck and fortitude! We run our startup's chat infra on matrix/element and this bug has lead almost to a team mutiny. Hope it get's resolved soon!

**Comment by alexander-potemkin** [comment]
> Sending all the dev working on resolving this issue lots of good luck and fortitude! We run our startup's chat infra on matrix/element and this bug has lead almost to a team mutiny. Hope it get's resolved soon!

We ended up switching... People were missing important messages, things got lost, we end up keeping our server as an archive, but considering the time it took to only start active investigation, the decision has been made to switch from Element (as the only very much active and full-featured client of Matrix).

It only makes sense for me in security related sphere, but given that there is no single reliably working client (FluffyChat is a good candidate, but luck active bugs fixing), it's a problem as well.

**Comment by colans** [comment]
Maybe this is a crazy idea, but given the gravity of the situation here (folks are switching away), how about reverting the fix for the issue that exposed all of this?  It seemed to work well enough before.

Keep it in a branch, and then get all of the follow-up issues working in there before merging.  What do you all think?

**Comment by t3chguy** [comment]
> Maybe this is a crazy idea, but given the gravity of the situation here (folks are switching away), how about reverting the fix for the issue that exposed all of this? It seemed to work well enough before.

At this point we'd need to revert 20-30+ PRs, the likelihood of missing one and making the situation even worse is high.

**Comment by Johennes** [comment]
To add to that, this isn't a trivial regression where a commit introduced a bug and can be backed out again. We started seeing a class of stuck notification problems after threads moved out of labs. Going back to the working state before would require not just reverting the various incremental fixes made so far but also  [re-labsing threads](https://github.com/vector-im/element-web/issues/25676) (since we have made the fixes for a reason).

**Comment by alexander-potemkin** [comment]
> To add to that, this isn't a trivial regression where a commit introduced a bug and can be backed out again. We started seeing a class of stuck notification problems after threads moved out of labs. Going back to the working state before would require not just reverting the various incremental fixes made so far but also [re-labsing threads](https://github.com/vector-im/element-web/issues/25676) (since we have made the fixes for a reason).

To be perfectly honest, thread’s didn’t work very well in that perspective when in the labs. Probably better then now, but it could be just a cumulative thing

**Comment by Johennes** [comment]
Yes, point taken very much that threads probably moved out of beta prematurely.

**Comment by rgpublic** [comment]
The only thing I don't understand is: Why can't the apps temporarily store the message-IDs that have been read locally (or at least the ID of the last read message in a room if that's too much data) until this is resolved? This would alleviate the problem a lot. It doesn't happen on mobile for me, BTW. And I don't have threads enabled either.

**Comment by Valodim** [comment]
Folks, this is a complicated issue spanning multiple months of work and many PRs already, it's escalated as far as can be. Piling more pressure on top or "how hard can it be, did you try simply doing X?" is unlikely to move things along faster at this point.

Let's please try and keep this issue focused on progress reports from the team to make it easy for everyone to follow along.

**Comment by samim23** [comment]
I appreciate all your hard work to get this resolved, thank you so much! I do wonder if the indicated time-frame ("change will appear in the release on 1st August") is the optimal course of action with such critical bugs, that are clearly damaging to the project brand and core user experience.

**Comment by mutantcornholio** [comment]
> I appreciate all your hard work to get this resolved, thank you so much! I do wonder if the indicated time-frame ("change will appear in the release on 1st August") is the optimal course of action with such critical bugs, that are clearly damaging to the project brand and core user experience.

Even though my own experience with stuck notifications is terrible, let's not rush the devs to make it two weeks earlier (we've been experiencing this for how long?). We know what happens with releasing stuff too early.

**Comment by andybalaam** [comment]
To aid debugging, here are some scripts we can use to gather information when debugging this:

Find my receipts in the Client for a room: https://gist.github.com/andybalaam/a20f44e24688378a659a6ed7f22f5944

Find my receipts in the Sync Accumulator for a room: https://gist.github.com/andybalaam/8c1f89434a0625bbe84553bac66d4520

Find my receipts in the Sync Accumulator for a thread in a room: https://gist.github.com/andybalaam/1548f9a5f1cd782c733d627e64dc4e12

To run these **you will need to edit the scripts** to insert the correct room ID and thread ID.

**Comment by andybalaam** [comment]
> I appreciate all your hard work to get this resolved, thank you so much! I do understand things take time ("change will appear in the release on 1st August") but frankly still wish it was solved sooner in production (my entire startup team using element is complaining to me daily about it.)

Thanks! This delay reflects our normal release process. The fix happened after our recent release candidate (11th July), so it won't appear in our next release (18th July) but it will go into the one after that (1st August). This process gives us time to test changes before we release them, which is critical to reduce the chances of releasing a nasty bug.

In the meantime you are welcome to try it out by using nightly builds or the develop.element.io URL.

**Comment by andybalaam** [comment]
**Late-arriving update** (might please @samim23 ;-)

We discussed this a little more, and we are quite confident in the fix that went in recently - we think it has made the situation better for us, and we think it has low risk, so we backported it to our next release candidate, and if all goes to plan it will be included in the release on Tuesday 18th July.

**Comment by jtrees** [comment]
Just wanted to say thanks to the team (in particular @andybalaam) for communicating like a champ and keeping us in the loop as of late. Can't speak for others, but it makes a massive difference to me and is rebuilding my faith in the project.

**Comment by leonardehrenfried** [comment]
I've been testing develop.element.io and I can say that it has resolved a large proportion of the "stuck room notifications" issues. Well done!

**Comment by aurorasmiles** [comment]
Running 1.11.36 for 3 days now and so far all the "stuck" notification issues seem to be gone, at least for me. I still get occasional unread badges in rooms even though there are no new messages, but they are no longer stuck or climbing into the hundreds.

**Comment by samim23** [comment]
> Running Element 1.11.36 & Synapse 1.88.0 for 3 days now and so far all the "stuck" notification issues seem to be gone, at least for me. I still get occasional unread badges in rooms even though there are no new messages, but they are no longer stuck or climbing into the hundreds.

I second this, the situation has much improve! Thanks to all the devs for the hard work on this!

**Comment by andybalaam** [comment]
Update for today:

* Tuesday's release [v1.11.36](https://github.com/vector-im/element-web/releases/tag/v1.11.36) came with a fix that removes stuck unreads for many cases.
* The next release, scheduled for 2023-08-01, will have another related fix that should remove 99% of stuck unreads (we think)
* Those 2 fixes led us to make [MSC4037](https://github.com/matrix-org/matrix-spec-proposals/pull/4037), which we believe fixes a bug in the spec. We will continue working to get this spec change accepted.
* Stuck unreads are still possible, when the timestamps of messages don't match the order they are stored in Synapse, especially in threads. We think this is rare in practice. To fix this, we need [MSC4033](https://github.com/matrix-org/matrix-spec-proposals/pull/4033)
* A separate problem exists, where rooms become unread when you restart the app. We are working on fixing this.
* Another separate problem exists, where notification counts ramp up and down quickly under certain circumstances. We are working on fixing this.

Just for fun, if you're interested in why this is a difficult problem to fix, you might be interested in our [proposed set of test cases](https://github.com/vector-im/element-web/issues/25449) that we intend to write to make sure it works as expected. At the time of writing, we have identified **146 cases we need to test**, and we are not at all convinced we've listed them all. Hopefully this also encourages you that when we have all those test cases, the behaviour of the app in this area will be considerably more stable.

**Comment by Johennes** [comment]
The topmost task list in the issue description has been updated with our latest plan of attack. Following on from the impactful fixes we've made in the past two weeks, we believe there are more code-level problems we can solve and, thus, are slightly deprioritizing pushing through on the MSCs.

**Comment by jplatte** [comment]
It's definitely gotten a lot less common, but just caught it another time, this time it's *properly* stuck (not even reacting and removing the reaction again helps): #25846

**Comment by jtherrmann** [comment]
I have a single notification from someone who `@` tagged me. The notification shows up in the browser tab icon as well as in the Notifications menu. I've viewed the message but the notification is still there. Is this a stuck notification, or is there some way to clear it from the Notifications menu?

**Comment by t3chguy** [comment]
We are continuing work in this area; the release gone out today carries yet more fixes for stuck notifications and yet more are awaiting review for "zombie notifications" (a phenomenon where notifications you have cleared come back on reloading the app). We're now focusing on creating a swathe of tests to aid in a major refactor to the threads data model which we believe will help with the stuck notifications project but also help fix some threads bugs.

**Comment by andybalaam** [comment]
We are continuing our work on this issue. We are investigating some open issues, and trying to close bugs that we think are already fixed. We have discovered some problems with our handling of unthreaded receipts (which are created when you choose "Mark Room As Unread") and we're working out how to tackle them.

We are continuing work on our [comprehensive test suite](https://github.com/vector-im/element-web/issues/25449) which will give us confidence that we have fixed most of the problems when it is passing.

We are working on [MSC4033](https://github.com/matrix-org/matrix-spec-proposals/pull/4033) because we think some of these issues are difficult or impossible to solve without it.

**Comment by mrclauss** [comment]
My issues I had are also resolved with this release, thanks a lot for all your effort!

**Comment by andybalaam** [comment]
We are seeing things improve for quite a few users, but we know some problems remain, specifically in cases where message timestamps disagree with the order of messages as the server sees it, and when dismissing old threads by using Mark Room as Read.

We are continuing to work on these problems. We are writing [tests](https://github.com/vector-im/element-web/issues/25449) that cover all the problems we have seen. Some of these currently fail, which helps us keep track of what situations still don't work correctly.

The next step after writing the tests will be to work on a change to the spec: [MSC4033](https://github.com/matrix-org/matrix-spec-proposals/pull/4033). This will remove the existing ambiguities about what order events are in, making the job of deciding which events are read much simpler. We will prototype this change, and if it solves the problems as we expect (the tests will help to know), we will continue to push for it to be included in the Matrix spec and implemented in homeservers.

If anyone reading continues to see problems, and can reproduce them consistently, bugs that describe clearly how to trigger a problem are still appreciated. For those who are able, what would be even better would be a new test within the [test file](https://github.com/matrix-org/matrix-react-sdk/blob/develop/cypress/e2e/read-receipts/high-level.spec.ts) that fails because it triggers the problem.

Thank you again for your patience. I think we have a good plan for how to squash these problems and never see them come back!

**Comment by andybalaam** [comment]
Work continues this week on improving and fleshing out the comprehensive [test suite](https://github.com/vector-im/element-web/issues/25449). Next on the list after that is working on MSC4033.

**Comment by leonardehrenfried** [comment]
I'm impressed with this thorough engineering approach you've taken to solving the problem.

**Comment by andybalaam** [comment]
We are continuing with the work of filling out the test suite, although I've mostly been fighting vagaries of the CI setup this week :-). At some point soonish we will probably double the size of the suite by allowing tests to run in both encrypted and unencrypted rooms, since we expect different behaviour in quite a few cases (because the server can't examine encrypted messages to give an accurate unread count).

**Comment by andybalaam** [comment]
![image](https://github.com/vector-im/element-web/assets/76812/4d04f59c-89ab-4b1c-97cc-2c7c70a21553)

Progress on writing test cases: the number of implemented cases rose from 46 to 70, with the total expected nunber of cases now at 155.

I do expect the number of cases to double at some point when we allow tests to be run either encrypted or unencrypted mode.

A breakthrough this week: one of the tests uncovered a remaining stuck unread case: "Reading an unread thread after a redaction of the latest message makes it read" so when we make that test pass we know we will be removing real stuck unreads that people experience.

**Comment by andybalaam** [comment]
![image](https://github.com/vector-im/element-web/assets/76812/bff653e3-d163-4a68-b988-965d606a028f)

77 test cases implemented out of 155, after a slow week with security releases and day-to-day maintenance duties interfering. I'm hoping to make faster progress this week.

**Comment by andybalaam** [comment]
![image](https://github.com/vector-im/element-web/assets/76812/530ab99c-af0b-4942-8e05-f1d203cb43ec)

106 tests implemented out of 156. We are moving our focus on to figuring out why some of these tests sometimes fail randomly - I suspect some of them are actually real problems in the app. Once the tests are stable, we will work on fixing some of the problems we have already found, before continuing with the test suite.

**Comment by jeffrson** [comment]
I hope this will be fixed soon. Since this is the thread where all (new) issues are linked to, I will add some observations. I don't know, if all these are covered by test cases yet.

Notifications are stuck if:
* last message in a room is actually in a thread (can be "fixed" sometimes by posting a new message to the room)
* notifications in threads are especially hard to get rid off, if they have been edited by their author
* last message (or event) is a reaction

Sometimes notifications reappear in old threads.

"Mark room read" does not solve the problem - sometimes not even for the moment, but if so, after reloading the notification return.

Recently it's not only the "bold" state that appears, but also "red" with an apparently random number, often quite large.

**Comment by omame** [comment]
I noticed that when "Mark as read" doesn't work, reacting to a message clears the notification.
So when this happens to me (and it still does happen very often) I click on an emoji reaction and remove it right away.

**Comment by andybalaam** [comment]
113 tests implemented out of 157:

![image](https://github.com/vector-im/element-web/assets/76812/1a50dc75-db21-47c9-9467-753789e3c856)

I have some maintenance tasks I need to work on this week, and after that I will start on looking at fixing some of those failures, which should (eventually) result in some of the remaining problems people are seeing being fixed.

**Comment by andybalaam** [comment]
![image](https://github.com/vector-im/element-web/assets/76812/1a6075ea-3924-4f7a-aa62-f8807c54e0f6)

This week we have been mostly fighting flaky tests. Many of the flakes are caused by unreliable behaviour by Element when messages are edited or redacted, so may well be linked to real stuck unread cases.

Our next step is to pick some test flakes or failures and fix them, hopefully giving real improvements for those of use experiencing stuck unreads.

**Comment by jtrees** [comment]
It's interesting that the number of failing tests wen up in October, despite no new tests being added. Perhaps sign of a regression?

**Comment by marco-c** [comment]
I have indeed started seeing the issue of stuck notifications way more frequently in the past few days.

**Comment by andybalaam** [comment]
> It's interesting that the number of failing tests wen up in October, despite no new tests being added. Perhaps sign of a regression?

Hmm. Maybe that chart is misleading - those failing tests are manually marked as failing. The reason the number went up is either:

* newly implemented tests that fail, or
* old tests that we thought were passing but realised are actually flaky

So any correlation between the numbers rising and the number of actual issues is almost certainly coincidental I'm afraid.

**Comment by andybalaam** [comment]
> I have indeed started seeing the issue of stuck notifications way more frequently in the past few days.

That is bad news, and probably indicates that something changed that is not currently covered by the tests. Any hints on what kinds of things are happening to cause these would be appreciated (e.g. did someone edit or delete a message, was it in a thread, etc.)

**Comment by marco-c** [comment]
Unfortunately it's hard to pinpoint, I'm seeing it both in a private conversation without any threads, modifications or anything else I can think of and in two rooms (both with threads, modifications, etc.).

**Comment by bhearsum** [comment]
I am not certain if it's totally new or not, but I have definitely noticed more stuck notifications around deleted messages in the past few days.

**Comment by andybalaam** [comment]
Investigating under #26363, I have discovered that redactions can cause messages to jump to another thread, but Element Web does not implement that behaviour. The spec proposal to fix this is: https://github.com/matrix-org/matrix-spec-proposals/pull/3389

@Johennes given my problem with updating this issue's description, please could you add this MSC at the top? Thanks!

**Comment by Johennes** [comment]
Have added it

**Comment by bhearsum** [comment]
Another data point for you: I've been using Nheko as a client for ~1 week or so now. Up until today I had zero stuck notifications at all with it. This morning I had one stuck notification which was quickly resolved by adding an emoji reaction to the latest message in the channel.

(If this sort of message is not useful please let me know and I'll stop posting here.)

**Comment by andybalaam** [comment]
> Another data point for you: I've been using Nheko as a client for ~1 week or so now. Up until today I had zero stuck notifications at all with it. This morning I had one stuck notification which was quickly resolved by adding an emoji reaction to the latest message in the channel.
> 
> (If this sort of message is not useful please let me know and I'll stop posting here.)

Interesting... My understanding is that Nheko displays all messages in the main timeline (with annotations to indicate threads), and only uses unthreaded receipts. I have heard of some stuck notifications in rooms without any threads, but they are certainly much rarer. My guess would be that the order of messages was somehow inconsistent between the client and server, so the server did not accept a "later" receipt, which it considered to be "earlier".

**Comment by andybalaam** [comment]
Update on this issue: the graph looks mostly unchanged this week, but we have started work on fixing some of the issues made clear by failing tests. This PR: [matrix-js-sdk#3798](https://github.com/matrix-org/matrix-js-sdk/pull/3798) fixes several redaction tests, and will be merged after the release candidate branch has been made, to allow us maximum time to test in practice whether it makes things better or worse.

**Comment by samim23** [comment]
Another data point for you: The issue with stuck notification was significantly better about 1 month ago. The past 2 weeks about, things feel like they have gotten worse again. Today even the trick of saying on a channel "mark all as read" stopped working for me, the unread notification simply stay there. 

Fun sidenote: One of our channels had a confetti emoji (which triggers this big onscreen animation) somewhere in the distant past. For some reason, this frequently gets flagged as unread and re-triggered, leading to a somewhat confusing confetti party. 

Following this thread, i am aware how complex and far-reaching this set of related bugs is, and i salute all the developers ongoing massive efforts to get this resolve - i'm rooting for you all!

**Comment by colans** [comment]
I just ran into https://github.com/vector-im/element-web/issues/25479, but when I select Mark Unread on the room (not after restarting).  Is this the same ticket, is there another one for this, or should I create a new one?

**Comment by andybalaam** [comment]
Update for this week - the redaction-related fixes are merged and released. I am working on fixes that affect editing messages.

**Comment by colans** [comment]
> Sounds like a new ticket. Do you mean "Mark as read"?

Yes indeed I do; sorry.  New ticket is https://github.com/vector-im/element-web/issues/26475 .

**Comment by andybalaam** [comment]
> Update for this week - the redaction-related fixes are merged and released. I am working on fixes that affect editing messages.

Correction - the redaction-related fixes are merged and included in today's release candidate, which will be released next week.

**Comment by andybalaam** [comment]
Update: I have found some incorrect assumptions in the code that stores and retrieves receipts inside matrix-js-sdk, so I am working on a change that will restructure this. I think it can explain some of the incorrect answers about what is read that we have been seeing.

**Comment by andybalaam** [comment]
I confess I've delayed this week's update until I could include this graph:

![image](https://github.com/vector-im/element-web/assets/76812/7f570121-8cdf-434e-af02-7df9ed76bc99)

... which shows some of the effects of a lot of work that has been going on behind the scenes. The little drop in the red and green lines on the right-hand side represent a **reduction in the number of known stuck notification bugs** in the development version of the code. Most of the drop so far comes from [a PR ignoring invalid receipts](https://github.com/matrix-org/matrix-js-sdk/pull/3817).

We fully expect this to **reduce the number of real-world problems** people are experiencing. Note: reduce the number, not eliminate (yet).

We also had a slight false-start this week, where we had to [revert changes](https://github.com/matrix-org/matrix-js-sdk/pull/3858) to move deleted messages to the main timeline because they caused a [bug](https://github.com/vector-im/element-web/issues/26498) we fixed very late in the release cycle. However, we now have a [proper fix](https://github.com/matrix-org/matrix-js-sdk/pull/3862) for this problem, and we expect to "unrevert" the revert just after the next release candidate. (The timing here allows us time to test this change, which is disruptive, on the bleeding-edge deployment at develop.element.io for as long as possible before releasing.)

Meanwhile, we have found some limitations in the way receipts are stored in matrix-js-sdk, which explain some of the other problems we are seeing, especially with "Mark room as read" not working as expected. We are re-writing the receipt-handling code to reflect our new understanding, which won't be super-fast, but we are hopeful that it will make a big difference.

I know this process is painfully slow when viewed from the outside, but rest assured we are working hard on it, and we are working in an organised and systematic way, using the tests as the source of truth. This means that when we take one step forward, we are less likely to take two steps back and cause new bugs with our fixes. For an explanation of how complex some of the logic we are working through here is, check out my [recent Matrix Live video](https://www.youtube.com/watch?v=K4NJLkStH9g).

**Comment by andybalaam** [comment]
Related: https://github.com/matrix-org/element-web-rageshakes/issues/23166

**Comment by andybalaam** [comment]
Update: we will unrevert the fix for moving deleted events to the main thread today, so it will be in the release in 3 weeks. We continue to work on the rewritten receipt storage and expect to have the first change ready this week. It will then need more time to be completed, but we should see further improvements to the experience of stuck unreads next week, if we make the progress we are hoping for.

**Comment by jeffrson** [comment]
During the last days several messages notify multiple times after reloading element (-web, not the app) with Chrome, at least. This **may be** related to recent update of chrome, though. Nothing else changed, afaict.

**Comment by andybalaam** [comment]
Update:

* ~2 weeks until release 1.11.51 which will contain the first tranche of fixes - for deleted messages, and a general fix to ignore invalid receipts.
* Meanwhile, we are working on PRs https://github.com/matrix-org/matrix-js-sdk/pull/3901 and https://github.com/matrix-org/matrix-react-sdk/pull/11903 that start the process of rewriting the receipt-handling code. There is more to do to replace the previous implementation fully.
* I am moving to an adjacent team, so won't be writing these updates in future, but I will still be helping out, and the team is continuing to work hard on this!

**Comment by azmeuk** [comment]
> I am moving to an adjacent team, so won't be writing these updates in future, but I will still be helping out, and the team is continuing to work hard on this!

@andybalaam your recurrent reports on how things are moving are hugely appreciable. Will the team keep up those reports when you move on?

**Comment by andybalaam** [comment]
> @andybalaam your recurrent reports on how things are moving are hugely appreciable. Will the team keep up those reports when you move on?

Hi, I'm really glad they have been helpful. Yes, the team (not sure who yet!) will continue reporting progress here.

**Comment by andybalaam** [comment]
> Just to point out that Element Desktop for Mac (and probably its other siblings) version `1.11.51` behaves way better with respect to notifications, so your effort was not in vain.

That is great news. I know there are more big changes coming, and the bleeding-edge version is working really well for me today, so I am hopeful that we are turning a corner.

**Comment by florianduros** [comment]
**Update**

 About our stuck notification test cases:

<img width="588" alt="image" src="https://github.com/element-hq/element-web/assets/2621378/94e9d605-36b1-4408-b4ca-07977655c8d2">

As you can see, we are facing a large drop on our failing tests 🎉.
Multiple reasons behind this drop:
1. The receipt rewrite has landed on develop. We were able to enabled a bunch of our skipped/failing tests thanks to this rewrite. We also noticed a large drop of notification/unread on develop in our daily usage.
2. We fixed also additional bugs
3. We moved our end-to-end tests from cypress to playwright. We had a lot of failing tests due to flaky (inconsistent failure between multiple runs) behavior and the migration fixed this flackyness
4. Rewrite and fixing of test cases

We are aware that there are still issues and we have to write more tests but this result is already a big step forward!

**Comment by krachynski** [comment]
I have several rooms with threads that refuse to be marked as read. One thing I noticed with this is that the last message in each thread has been edited.

**Comment by florianduros** [comment]
> I have several rooms with threads that refuse to be marked as read. One thing I noticed with this is that the last message in each thread has been edited.

Thanks for your return. We saw also that when the last message in a thread is a reply, the thread stays unread.

**Comment by leonardehrenfried** [comment]
I'm going to risk repeating myself but I just want to show my gratitude for staying on top of this monstrously complex problem. It's been a long slog and it starting to look like you're close to resolving it. Well done.

**Comment by MightyCreak** [comment]
I don't know how related it is to this issue, but on Element Desktop, since a few weeks/months, I receive the notifications of people getting in and out of spaces, as well as avatar changes events.

It took time for me to figure it out, but although I disabled the notifications for these kind of events, I figured that it was linked to events coming from spaces only.

Hope it helps in this huge task to stabilize the notifications in Matrix.

**Comment by samim23** [comment]
Really appreciate all the efforts the dev's have put into this issue. As intensive matrix/element users, our entire team has been along for the stuck notifications journey. It felt like it was getting better a while back, but recently the amount of stuck notifications has sky rocketed again it seems and the behavior is very erratic, which makes it hard to fill a proper bug report here. One comedy aspect of it: If you had "confetti" anywhere in an old thread, it tends to get re-triggered regularly now, resulting in a spontaneous on-screen confetti party.

**Comment by vranki** [comment]
Commenting here as requested, although not sure if this is useful for fixing the issue. Element version: 1.11.52 (both web and desktop).

- On launch Element has lots of rooms marked unread, although they have no activity for long time and have been read before. 
- Viewing the rooms clears unreads for this usage session on most of rooms
- Some rooms still have stuck unreads. Right click -> Mark as read does not mark them read and they stay unread forever.

Note: This is without logging out or back in - just daily usage. There is no initial sync.

I have about 150 rooms. Maybe 20-30 of them are marked unread for no reason on launch and maybe 1-3 get stuck unread forever.

**Comment by benjaoming** [comment]
@vranki is there any kind of correlation between rooms with encryption enabled and "stuck unreads" ?

My sample is far from as big as yours, but I do find the issue more persistent in rooms with encryption enabled over the past months. Currently, I have 1 encrypted room "worst" affected, i.e. that "Mark as read" has no effect on it (no unread messages, no threads with any unreads, no encryption errors, no visible explanation at all) - and that room has encryption enabled. The impact is exacerbated because the stuck "unread" status propagates to the Community, so the Community persistently appears as having new, unread messages.

**Comment by ajkessel** [comment]
I have some rooms that always show false unread notifications every time I restart Element. I have one room in particular that only has three members but frequently shows incorrect unreads, even without restarting Element. That room probably has the most threads of any of my rooms, but it is showing unread notifications even when no new item is added to a thread. Sometimes "mark all as read" will clear it, sometimes not.

**Comment by vranki** [comment]
New bit of probably useless information: The room I had stuck forever yesterday became read via Right click -> Mark as read today on same client on same computer. I've used Element on other computers meanwhile. Probably some kind of interaction between different clients on the account affects this.

**Comment by MartinDelille** [comment]
I am experiencing some strange issue with thread notification:

- I am in a room with several thread opened that I already read
- When someone post in the room, some thread turns back unread

Shall I wait for this issue to be fixed ? Give more details here ? Create another issue ?

**Comment by samim23** [comment]
Since this issues keeps on lingering and seems hard to fix, would it be a possibility somehow to at least make the "mark as read" work as intended (in channel context menu)? For many month now, I'm consonantly being spammed by these random notification. Having one reliable button to say "I've read everything!" would be really awesome as quick fix.

**Comment by ajkessel** [comment]
> Since this issues keeps on lingering and seems hard to fix, would it be a possibility somehow to at least make the "mark as read" work as intended (in channel context menu)? For many month now, I'm consonantly being spammed by these random notification. Having one reliable button to say "I've read everything!" would be really awesome as quick fix.

Agree with this. Recent releases of iOS Element have "mark all as read" which I understand to mean mark all messages in all rooms as read, but that doesn't work reliably either.

**Comment by MartinDelille** [comment]
@adamcstephens could you explain you downvote [here](https://github.com/element-hq/element-web/issues/24392#issuecomment-1900333075) ? 

There is the following item in the check list of this issue : 
- [ ] Fix Zombie notifications from old threads – ? issue ?

I personaly encounter this issue where I have some old thread that turn unread when someone send a regular message in the room. It is unfortunately not automatic.

**Comment by leonardehrenfried** [comment]
I agree with the other posters about it getting worse. I have switched to https://develop.element.io and there most (all?) issues appeared to have gone away. 

https://github.com/matrix-org/matrix-js-sdk/pull/4022 seems to have removed a large number of bugs. Well done, @florianduros .

**Comment by florianduros** [comment]
The fixes of the last weeks are available on [develop.element.io](https://develop.element.io/). They are fixing the last case of stuck unread and a lot of zombie notifications.

Some cases of zombie notifications are remaining, clearly less than before but still annoying! We will investigate on it :)

**Comment by j-nava** [comment]
I've been using [develop.element.io](https://develop.element.io) for quite a while now and I can also attest that it's getting better and better. I can't wait for this to be completely fixed so I can convince more people to join my little community of friends. 😃

Keep up the good work!

**Comment by MTRNord** [comment]
Seems like since the latest changes I am back to notifications that cant be dismissed on any device. Only a clear cache works. This affects both ele-web and ele-android. So I wonder if its actually synapse causing it this time around :thinking:

**Comment by benjaoming** [comment]
@MTRNord 

> Seems like since the latest changes

Can you be more clear about which changes you refer to? In the comments immediately before yours, people are reporting success from [develop.element.io](https://develop.element.io/) so it's important to know if you are having a contradicting experience with the exact same version of Element.

**Comment by simonmichael** [comment]
When will the develop.element.io fixes be rolled out in Element desktop and mobile and Element X production/testflight ?

**Comment by MTRNord** [comment]
> @MTRNord
> 
> > Seems like since the latest changes
> 
> Can you be more clear about which changes you refer to? In the comments immediately before yours, people are reporting success from [develop.element.io](https://develop.element.io/) so it's important to know if you are having a contradicting experience with the exact same version of Element.

I dont really have an exact commit but it happened to start like that after the crypto upgrade on friday(?) on develop while being on fosdem.

**Comment by ajkessel** [comment]
Still experiencing this problem daily in multiple rooms with latest develop.element.io as well as the regular web/desktop release and on iOS Element from TestFlight, using Synapse 1.101.

What's really perplexing is how random it is. Unread notifications show up in random old threads that haven't been touched for a while. There seems to be no precipitating event or rhyme or reason as to what triggers the notification.

Usually, "mark all as read" clears it now, at least temporarily, which is some progress.

Is there any client- or server-side logging I could do to try to isolate the cause more systematically?

**Comment by iyanmv** [comment]
Maybe someone can do a quick update about the test cases? @florianduros ?

**Comment by florianduros** [comment]
@iyanmv https://github.com/element-hq/element-web/issues/25449 we closed the issue about the test cases. We assume that we fixed the existing tests and we are satisfied with the current tests. Of course, when we are fixing bus around notifications we are adding new tests.

**Comment by jo-so** [comment]
My [original report #8941](https://github.com/element-hq/element-web/issues/8941) was about rooms flagged as having new messages after login or cache reset, but they don't have. This issue was closed in favour of this one, but yesterday, I've logging in on a new session and still got stale room notifications. Does anything happen to this issue?

**Comment by mutantcornholio** [comment]
After each time I restart Element, I have to go over 10-15 chats, to mark everything as read. I feel like it's connected to the fact that messages are being loaded when I click the conversation, not when I open Element, but that's just a guess.

**Comment by mutantcornholio** [comment]
Also, opening chats for the first time after restarting element, when the messages are loaded, marks some of the loaded ancient messages from threads as unread.

**Comment by mutantcornholio** [comment]
> Also, opening chats for the first time after restarting element, when the messages are loaded, marks some of the loaded ancient messages from threads as unread.

One more thing that I've noticed, is a lot of times the ancient messages are stuff like `Alice invited Bob`, or `Alice changed the power level of Bob from Default to Admin`, or `Alice made the room invite only`. Happens far more often in comparison to active chats, where people actually send messages.

**Comment by ajkessel** [comment]
Has progress stalled? I've had the same stuck unread notifications for several months now, both on every production release of Element as well as running bleeding edge from develop.element.io. It does seem to be the same rooms/old messages that consistently show as unread. Is there anything I can do as an end-user to troubleshoot the circumstances, particularly where the issue is reproducible at least for some fraction of the time?

**Comment by mutantcornholio** [comment]
Any update?

**Comment by JMoVS** [comment]
Is there still work on threads becoming unread again and again all the time? Happens quite frequently to me nowadays

**Comment by MTRNord** [comment]
> Is there still work on threads becoming unread again and again all the time? Happens quite frequently to me nowadays

I also have this. In foundation room I get a loud ping for a mention in a thread each time a new message is added to the room. Its annoying me.

**Comment by dreirund** [comment]
> *Is there still work on threads becoming unread again and again all the time? Happens quite frequently to me nowadays*

I have this, too.

**Comment by HelderFSFerreira** [comment]
I have more than 30 rooms stuck notifications.

Mark everything a read does not work. Let me know if I should provide any logs.

**Comment by JMoVS** [comment]
are there more logs required or anything? This issue has been around for more than a full year now and recently progress seems to have stalled

**Comment by langleyd** [comment]
Thanks all for the continued patience and feedback on this issue and apologies for it becoming stale.

A lot of progress was made in 2023 and Q12024 on spec, bug fixes, tests and also improvements to the UX on notifications including:
- Removing threads activity(white dots caused by threaded messages) from the main room list
- Adding the Thread Activity Center(thread button bottom left) specifically for thread notifications.

You can check out [this blog post](https://element.io/blog/ess-24-05-now-with-element-desktop-msis/#:~:text=Threads%20and%20notifications%20supercharge%20productivity) for some more details on the improvements.

We hope these efforts have brought a somewhat calmer and improved experience for notifications, especially on the main room list.

We are aware there are still problems, particularly in the threads experience. We suspect some of the bugs in threads related to activity indicators(white dots) are caused by a bug in synapse and are pursuing [this](https://github.com/element-hq/synapse/issues/17247) as a next port of call. (@JMoVS We suspect this is the source of the bug you and others have highlighted above).

Aside from ongoing efforts to fix particular known bugs, we know where we are currently with notifications is not the destination. For example, while we believe the new threads activity centre creates a calmer experience there is a risk of missing out on threaded messages. One thing we would like to do in future is introduce Thread Participation to opt in to notifications for specific threads. This would allow us to improve the UX and value delivered by the Threads Activity Center. However before we tackle another major iteration on Notifications we need to first make some foundational improvements to how both room list/spaces and the timeline work. We’ll update again when we have more to share.

**Comment by mutantcornholio** [comment]
Love the progress, but this still doesn't say how are we doing on actually fixing bugs related to notifications. Why are there still notifications reappearing after restart, and what's the timeline on fixing those?

**Comment by wielinde** [comment]
Another source of frustration is UX related: I have about 100 rooms in various spaces. The list does not fit on a single screen. The room list is not sorted by last activity which makes me miss notifications below the first fold. If I miss notifications the tool loses the trust. If Element had a room list ordered by activity then this would constitute a real inbox and resolve a lot of anxiety of missing messages. 

BTW I also believe that Threads should ideally have titles so that it becomes easier to jump back. Also threads could then be treated similar to rooms within such inbox. However, one should be able to mark a thread as closed/resolved. Zulip does that part very well.

**Comment by vranki** [comment]
> Another source of frustration is UX related: I have about 100 rooms in various spaces. The list does not fit on a single screen. The room list is not sorted by last activity which makes me miss notifications below the first fold. If I miss notifications the tool loses the trust. If Element had a room list ordered by activity then this would constitute a real inbox and resolve a lot of anxiety of missing messages.

This is not related to "Stuck notifications" issue so better report and discuss it elsewhere. But anyway right-click on "Rooms" header and you can choose to show rooms with activity first.

**Comment by mehlkopf** [comment]
That's my Element on iOS. I do not know what is wrong there, as the situation is much better on my Mac client, but neither mark all as read nor deleting the cache helps clearing these unread notifications. So for me personally, this is still a dumpster fire.
![IMG_B459D536F468-1](https://github.com/user-attachments/assets/71a511bb-bd81-41cf-ac50-afa5b7e9b60d)

**Comment by nebocamin** [comment]
i dont know where it fits but want to share an observation.
i have a lot stuck unreads, but i dont see them with desktop element under macos, but on linux and it doesnt matter if i use stable or nightly element (2nd load after deleting cache).

**Comment by leonardehrenfried** [comment]
An observation: For me clearing all cookies and local storage has managed to get rid of a very persistent notification. Not that it should be necessary though...

**Comment by leonardehrenfried** [comment]
An observation: For me clearing all cookies and local storage has managed to get rid of a very persistent notification. Not that it should be necessary though...

**Comment by nebocamin** [comment]
> An observation: For me clearing all cookies and local storage has managed to get rid of a very persistent notification. Not that it should be necessary though...

i just started a completely new session on a new device using linux and after the second start, all my 8 friends (well known stuck notifications) are here again. in the meantime on macos using element-desktop still clean. i have no clue.

**Comment by ebousse** [comment]
Many of my rooms currently have "stuck" unread notifications. By "stuck" I mean that I can remove the unread notifications (eg. with "mark as read"), but they all come back when I reopen Element web.

What is strange is that I had not encountered this sort of problem in months, and it started coming back since ~1-2 weeks.

I sent logs through Element Web, using this issue as recipient.

**Comment by dreirund** [comment]
> *Rageshake is here: https://github.com/element-hq/element-web-rageshakes/issues/28074*

Gives me an HTTP error 404 "Not Found".

**Comment by TheFibonacciEffect** [comment]
I had the issue that I read all the rooms, but somehow there was still the number 19 displayed at "home" even though not a single room had unread messages. The number 1 was displayed in the system tray to show that I had unread notifications. However there is a manual way of marking all notifications as read. Go to Settings > Notifications, there is a red button that says "Mark all as Read". That worked for me.

**Comment by davidegirardi** [comment]
> > _Rageshake is here: [element-hq/element-web-rageshakes#28074](https://github.com/element-hq/element-web-rageshakes/issues/28074)_
> 
> Gives me an HTTP error 404 "Not Found".

Those are for the internal dev team.

**Comment by vranki** [comment]
>Go to Settings > Notifications, there is a red button at the bottom that says "Mark all as Read". That worked for me.

I have a hard stuck notification (DM room) that still stays unread after "Mark all as Read". Right click -> Mark as read marks it for current session, but next time I open Element it's always back.

**Comment by domestomas** [comment]
Any time i restart element desktop, i have multiple unread threads in one particular room :/ Does it make sense to report such things or do we consider stuck notifications generally known issue?

**Comment by ajkessel** [comment]
> Any time i restart element desktop, i have multiple unread threads in one particular room :/ Does it make sense to report such things or do we consider stuck notifications generally known issue?

Same here, for years. I'm not sure anyone is really engaging with this issue on the developer side. It's crazy that you can't just "mark all as read" and have it consistently stick between sessions.

**Comment by mutantcornholio** [comment]
@langleyd Can we get any update on this? We're all experiencing the same issue for years.

**Comment by jeremie-lesage** [comment]
It's the same here. Users are asking to leave Matrix because they're fed up with this bug.
How can we help solve this problem?

**Comment by MightyCreak** [comment]
I, for one, didn't encounter this bug for a long time. I'm using Element Web and Element X (for Android).

The only "bug" I still have now is that even though I've read a message in Element Web, the notification (from the OS notification system) stays up.

**Comment by olivierlambert** [comment]
Hi,

Considering switching from Mattermost (less and less Open Source) to Matrix/Element, but this issue is really raising concerns internally (as it's tested at small scale). I'm using it for some Open Source project (like Xen Project) and I always have inconsistent notifications despite reading threads.

So same question: is there anything that could be done to help solving this, or is there any alternative client that do not experience this problem?

**Comment by alexander-potemkin** [comment]
> is there any alternative client that do not experience this problem?

Cinny, if you don't mind missing some of the features and element calls is one of them

**Comment by ajkessel** [comment]
I haven't seen this issue on Element-X but it lacks real threads support.

**Comment by alexander-potemkin** [comment]
> I haven't seen this issue on Element-X but it lacks real threads support. 

... and it's not a desktop app, unless I'm missing something?

**Comment by ajkessel** [comment]
Oh, right. For desktop, gomuks is great and evolving much faster than Element. It currently has limited threads support but lacks search. Those are both on the roadmap.

**Comment by rgpublic** [comment]
Some app doesn't have this. Some app doesn't have that. They all don't deliver the same features, platform availability and convenience as Element. I really wonder why this doesn't get more attention. I have this problem literally every day. I start the day opening the Element app on my phone and enter different chat rooms to read the unread messages there. When I now turn on my desktop computer and open the Element-Web application, I have unread messages in all those rooms. Every day. Every time. I always have to mark all messages as read manually so that the badge with the number disappears. Not even clicking on the room and reading the messages again helps. Is there really no way to make this work at least a little bit better? At least a checkbox option: "[x] Mark all messages as read when I enter the room" would be so much more convenient.

**Comment by ccoenen** [comment]
> Some app doesn't have this. Some app doesn't have that. They all don't deliver the same features, platform availability and convenience as Element. I really wonder why this doesn't get more attention.

This is the exact problem that killed XMPP.

"My client and your client both can do message carbons, but your server doesn't support the XEP, yet, so it doesn't work". On top of that "I want to use OMEMO, but my preferred client doesn't support it, yet". This is why I dropped XMPP a couple of years ago. It's just not worth the hassle.

This problem needs active management so that it doesn't affect users too much. I don't see any of the necessary work being done for matrix. Basically, everyone is using element, the Microsoft Office 365 of messengers. Whoever doesn't comply is expected to eat all the incompatibility overhead.

**Comment by samim23** [comment]
> This problem needs active management so that it doesn't affect users too much. I don't see any of the necessary work being done for matrix. Basically, everyone is using element, the Microsoft Office 365 of messengers. Whoever doesn't comply is expected to eat all the incompatibility overhead.

well said and criticality important point. More broadly, the matrix/element ecosystem feels like it's not living up to its fullest potential. One does wonder why...

**Comment by simonmichael** [comment]
As we can see from the issue history, the problem is complex and multi headed, and was being actively managed at least in 2023. Quite possibly it’s currently somewhat paused for lack of resources.

**Comment by alexander-potemkin** [comment]
> Oh, right. For desktop, gomuks is great and evolving much faster than Element. It currently has limited threads support but lacks search. Those are both on the roadmap.

... latest [release](https://github.com/gomuks/gomuks/releases): ~1 year ago... - doesn't look very much alive, doesn't it?

**Comment by ajkessel** [comment]
> > Oh, right. For desktop, gomuks is great and evolving much faster than Element. It currently has limited threads support but lacks search. Those are both on the roadmap.

>... latest [release](https://github.com/gomuks/gomuks/releases): ~1 year ago... - doesn't look very much alive, doesn't it?

[1600 commits](https://github.com/gomuks/gomuks/commits/main/), including dozens this month. It visibly improves daily. Also status updates on [Tulir's blog](https://mau.fi/blog/tags/gomuks/). It's just not getting frozen as releases but [CI binaries are available](https://mau.dev/gomuks/gomuks/-/pipelines) daily and it is also easy to compile. 

I believe there are Docker and Android builds available as well.
