### ISSUE TITLE
Icon on top/right (Ubuntu) has become very small (regression)

### ISSUE THREAD

**Issue by Norbert80** [vector-im/element-web#24440]
### Steps to reproduce

![grafik](https://user-images.githubusercontent.com/6921696/216826602-553ee878-f2c4-4dcb-9713-f84b7b9fed72.png)

![grafik](https://user-images.githubusercontent.com/6921696/216826607-c38955a1-ee68-447e-975f-57147cf67d83.png)

#### What did you expect?
Normal sized icon like in former Element Desktop builds.

#### What happened instead?
Icon is too small.

### Operating system

Ubuntu

### Application version

Version von Element: 1.11.22 Version von Olm: 3.2.12

### Will you send logs?

No

**Comment by andybalaam** [comment]
@Norbert80 is this installed via the official deb packages?

**Comment by Norbert80** [comment]
@andybalaam Hi, I think so:

![grafik](https://user-images.githubusercontent.com/6921696/217601049-86ab494f-fe29-4c68-a704-47dc9dd2a6ff.png)

**Comment by andybalaam** [comment]
This should be fixed in the latest release v1.11.23 (see https://github.com/vector-im/element-web/issues/23993 ) - please re-open this if it is not.

**Comment by Norbert80** [comment]
Bug still present in
Version von Element: 1.11.29
Version von Olm: 3.2.12
![element](https://user-images.githubusercontent.com/6921696/233719328-f5b3ca18-37ac-42f9-9ab8-eee497fb80b5.png)

**Comment by Norbert80** [comment]
> This should be fixed in the latest release v1.11.23 (see #23993 ) - please re-open this if it is not.

@andybalaam please re-open this issue.

**Comment by andybalaam** [comment]
Thanks for the report @Norbert80 - re-opening.
