### ISSUE TITLE
Errors in console likely linked to stuck unreads

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25642]
### Steps to reproduce

1. In a room, just browsing around
2. Look in the console

#### What did you expect?

Receipts to be sent without errors

#### What happened instead?

This error when some receipts are sent:

```
XHRPOST
https://matrix-client.matrix.org/_matrix/client/r0/rooms/!jSkNtsjcsXfCRJwGpp:matrix.org/receipt/m.read/$jdyMMc9_UwOUF1BSRcGekTmiGQvl5kIswe-juMwiRvw
[HTTP/2 400 Bad Request 29ms]
```

```
Error sending receipt 
Object { room: "!jSkNtsjcsXfCRJwGpp:matrix.org", error: M_INVALID_PARAM }
rageshake.ts:74:27
    fnName rageshake.ts:74
    instrumentConsole instrument.js:113
    methodFactory logger.ts:48
    sendReadReceipt TimelinePanel.tsx:1193
    TimelinePanel_TimelinePanel TimelinePanel.tsx:1163
    updateReadReceiptOnUserActivity TimelinePanel.tsx:1018
    componentDidMount TimelinePanel.tsx:325
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    setState MatrixChat.tsx:415
    viewRoom MatrixChat.tsx:978
    MatrixChat MatrixChat.tsx:695
    invokeCallback dispatcher.ts:120
    MatrixDispatcher dispatcher.ts:97
    sentryWrapped helpers.js:92
    (Async: setTimeout handler)
    _wrapTimeFunction trycatch.js:107
    dispatch dispatcher.ts:170
    viewRoom RoomViewStore.tsx:507
    onDispatch RoomViewStore.tsx:263
    invokeCallback dispatcher.ts:120
```

I've lost the response error message, but it was a 400 that said that the message was not in that thread.

I also see some messages like this in some rooms:

```
EventTimelineSet.addEventToTimeline: Ignoring event=$FIqf0uHppifN7Zgp9XWcrOEiXGhnKi58r1YK9F73Or0 that does not belong in timeline=!NasysSDfxKxZBzJJoE:matrix.org:2023-06-21T11:06:17.713Z timelineSet(threadId=undefined)
```

Rageshake (reported for a different issue): https://github.com/matrix-org/element-web-rageshakes/issues/21938

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
I believe this has been fixed

**Comment by andybalaam** [comment]
I do still get this message in my console, lots of times. Not sure whether that is expected?

**Comment by t3chguy** [comment]
@andybalaam definitely not expected. Please send logs as well as corresponding context from devtools > Notifications debug

**Comment by andybalaam** [comment]
Logs in https://github.com/matrix-org/element-web-rageshakes/issues/22359 show lots of "Ignoring event" messages. This was from a restart of the app. I don't see any stuck unreads as far as I know.

This is not specific to a particular room, so not sure it's helpful, but here is the notifs debug from the room I am currently viewing:

![Uploading image.png…]()

**Comment by andybalaam** [comment]
Here is the notifs debug from a room that is mentioned in the error message:

![image](https://github.com/vector-im/element-web/assets/76812/b25a8231-7c98-4db4-9ace-661e5fabd6b5)

**Comment by andybalaam** [comment]
^ That room contains no threads. It's a DM.

**Comment by andybalaam** [comment]
Here is an anonymised timeline from that room: 
[timeline.txt](https://github.com/vector-im/element-web/files/12250971/timeline.txt)

**Comment by t3chguy** [comment]
> I do still get this message in my console, lots of times. Not sure whether that is expected?

I thought you meant errors like `Object { room: "!jSkNtsjcsXfCRJwGpp:matrix.org", error: M_INVALID_PARAM }` - these are the ones which are signs of stuck notifications

The other ones are fine, they just mean we're not adding a reaction/relation to the timeline but still applying it in aggregate.
