### ISSUE TITLE
Cannot reject invite from a dead/malfunctioning homeserver

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4225]
### Description

I invited myself to a room from a test homeserver. That test homeserver has the capability to reach out, but not always be reached. The invite refuses to accept (obviously) and cannot be rejected. I should be able to remove this invite so I'm not stuck with a badge.

### Steps to reproduce

- Receive an invite over federation
- Have the sending server die
- Cannot reject invite

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by uhoreg** [comment]
Looks like  #3201, which was supposedly fixed by matrix-org/synapse#2145.

**Comment by jomat** [comment]
I still have this issue with synapse 0.21.1-1 & riot 0.11.2
Accept, reject, decline and decline all x invites won't remove it.
I got this invite from someone who discontinued his HS before I could accept it.
My HS logs this when I try to reject it:
```
2017-06-19 17:17:06,011 - synapse.access.http.8008 - 59 - INFO - POST-91910- 203.0.113.42 - 8008 - Received request: POST /_matrix/client/r0/rooms/!F5vdXD90urQdUrYxv2%3Aexample.com/leave?access_token=<redacted>
2017-06-19 17:17:06,012 - synapse.util.async - 206 - INFO - POST-91910- Acquired linearizer lock 'member' for key ('!F5vdXD90urQdUrYxv2:example.com',)
2017-06-19 17:17:06,013 - synapse.util.async - 206 - INFO - POST-91910- Acquired linearizer lock 'state_resolve_lock' for key frozenset([])
2017-06-19 17:17:06,013 - synapse.state - 326 - INFO - POST-91910- Resolving state for !F5vdXD90urQdUrYxv2:example.com with 0 groups
2017-06-19 17:17:06,016 - synapse.util.async - 213 - INFO - POST-91910- Releasing linearizer lock 'state_resolve_lock' for key frozenset([])
2017-06-19 17:17:06,017 - synapse.util.async - 213 - INFO - POST-91910- Releasing linearizer lock 'member' for key ('!F5vdXD90urQdUrYxv2:example.com',)
2017-06-19 17:17:06,018 - synapse.http.server - 123 - INFO - POST-91910- <XForwardedForRequest at 0x78305e28f364 method=POST uri=/_matrix/client/r0/rooms/!F5vdXD90urQdUrYxv2%3Aexample.com/leave?access_token=<redacted> clientproto=HTTP/1.0 site=8008> SynapseError: 404 - Not a known room
2017-06-19 17:17:06,019 - synapse.access.http.8008 - 91 - INFO - POST-91910- 203.0.113.42 - 8008 - {@jomat:example.edu} Processed request: 7ms (4ms, 0ms) (0ms/0) 66B 404 "POST /_matrix/client/r0/rooms/!F5vdXD90urQdUrYxv2%3Aexample.com/leave?access_token=<redacted> HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
```

**Comment by thekyriarchy** [comment]
was this supposed to be fixed by matrix-org/synapse#2145 ? it still is an issue for me

**Comment by nim65s** [comment]
Still ran into this issue

**Comment by t3chguy** [comment]
bumping prio as per https://github.com/vector-im/riot-web/issues/8943

**Comment by RebelCoderRU** [comment]
> Still got this issue, clearing riot's cache fixed it.

This does not work as this is not a local problem. All of my devices, logged in to my matrix account show that broken invite.

![Screenshot_20201004_095831](https://user-images.githubusercontent.com/20476773/95075085-46996680-0718-11eb-8295-4db9c78ab92c.png)
![Screenshot_20201004_095346](https://user-images.githubusercontent.com/20476773/95075087-4731fd00-0718-11eb-92d2-dcb2108aa81d.png)
![Screenshot_20201004_095315](https://user-images.githubusercontent.com/20476773/95075088-4731fd00-0718-11eb-93dd-2fdef522af27.png)
![Screenshot_20201004_095308](https://user-images.githubusercontent.com/20476773/95075091-47ca9380-0718-11eb-8c37-99c49c6a000b.png)

**Comment by t3chguy** [comment]
In which case the place to report your bug would be https://github.com/matrix-org/synapse/ as its Local Rejections are not working as they should be.

**Comment by t3chguy** [comment]
Closing in favour of a Synapse report, Synapse does local rejections but sometimes fails to inform clients down /sync - workaround is Settings > Help & About > Clear cache and reload
