### ISSUE TITLE
AuxPanel (Widgets, etc) push timeline down rather than occlude the top portion

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9377]

**Comment by bwindels** [comment]
Hmm, I thought this was intended behaviour as otherwise you wouldn't be able to scroll to the top part?

**Comment by turt2live** [comment]
I should probably clarify that this is when maximizing the widget. I don't think it's expected to have recent messages go missing when doing this.

**Comment by lampholder** [comment]
Ah, I think I understand - you're saying that you would expect opening the widget drawer to shrink the available space for the timeline, but whatever message was in position at the bottom of timeline window would still be where it was?

Like this? (GO GO GADGET ASCIIART)

```
+------------------------------------+      +--------------------------------------+
|                                    |      |                                      |
+------------------------------------+      |  COOL                                |
|  Bob: I like Riot.im               |      |       AND                            |
|                                    |      |              INTERESTING             |
|  Dan: Typing typing typing         |      |                             WIDGET   |
|                                    |      |                                      |
|  Bob: Drawing ascii diagrams fun   |      |                                      |
|                                    |      +--------------------------------------+
|  Dan: Is this what you meant?      |      |  Dan: Is this what you meant?        |
|                                    |      |                                      |
|  Bob: Yes, that's right            |      |  Bob: Yes, that's right              |
|                                    |      |                                      |
+------------------------------------+      +--------------------------------------+
|                                    |      |                                      |
|  Send a message (unencrypted)      |      |  Send a message (unencrypted)        |
|                                    |      |                                      |
+------------------------------------+      +--------------------------------------+
```

**Comment by turt2live** [comment]
Yes, because that's how it always worked until recently.

**Comment by turt2live** [comment]
ftr this isn't just about widgets - anything that goes into the AuxPanel space will do this, including search and pinned events.

**Comment by bwindels** [comment]
right, I see. When showing or hiding the AuxPanel, we should restore the bottom of the timeline, not the top.

**Comment by turt2live** [comment]
we fixed this

**Comment by SimonBrandner** [comment]
https://user-images.githubusercontent.com/25768714/142576620-818378ac-eed7-4745-b375-af43275ec683.mp4

Still an issue

**Comment by turt2live** [comment]
That's a different component - let's open a new issue with updated information please.

**Comment by SimonBrandner** [comment]
> That's a different component - let's open a new issue with updated information please.

Ah, didn't realize that
