### ISSUE TITLE
Read receipt animation sometimes has holes in it

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#9769]
I've observed this using riot.im/develop on Firefox (on GNU/Linux), read receipts sometime display with a hole in the middle:

![image](https://user-images.githubusercontent.com/5547783/58008113-9c4d7e80-7ae3-11e9-97cc-cf46f1fcd961.png)

If I click on the one at the right to expand the list, it expands correctly, and collapse correctly (like it should have been displayed in the first place, without holes) if I click again.

**Comment by turt2live** [comment]
Usually this is the media repo being slow or unresponsive. Does reloading the page help?

**Comment by babolivier** [comment]
> Usually this is the media repo being slow or unresponsive

I just saw that happen with read receipts from people with no avatar. The issue is that the second read receipt from the right seems to be "hidden" behind the first as when I click the one on the right the second one "slides" from behind it and fix the display.

**Comment by babolivier** [comment]
Here's one occurrence I managed to catch in the wild:
![Peek 2019-05-22 12-47](https://user-images.githubusercontent.com/5547783/58174609-31907480-7c96-11e9-8422-a56ee555e6e9.gif)

The animation is triggered by me clicking on the first avatar on the right.

**Comment by turt2live** [comment]
I can say I've only ever seen that behaviour when the media repo has a problem (the image fails to load, and it doesn't fall back to letters, which causes weird merging and artifacts). Some other side effects are read receipts sticking to the wrong events, etc.

Would recommend doing a hard refresh on the page, or opening the inspector, going to network, disabling cache, and refreshing.

**Comment by ara4n** [comment]
i've seen it even when the media repo is fine. there's been a long-term bug where sometimes the tetris algorithm races and fails, which brendan's screenshot shows (as delph & neilj collide)

**Comment by ara4n** [comment]
Relatedly, the alignment in general is getting worse and worse - e.g.:

![image](https://user-images.githubusercontent.com/1294269/69542666-db252b00-0f83-11ea-9a74-0cdd9b9fa012.png)

**Comment by babolivier** [comment]
Apparently still not fixed:

![image](https://user-images.githubusercontent.com/5547783/70334796-00e0e880-183e-11ea-8400-66724318a257.png)

Just witnessed now on latest develop. I saw Half-Shot RR dropping behind Amandine's, and it filled the hole when I clicked on a read receipt.

**Comment by uhoreg** [comment]
This may also be https://github.com/vector-im/riot-web/issues/3976

**Comment by Bubu** [comment]
This is basically happening for me constantly. A room switch fixes it, as does clicking the RR.

Before:
![image](https://user-images.githubusercontent.com/105185/84204820-31833280-aaac-11ea-9b14-4fd13b4981e8.png)

After click:

![image](https://user-images.githubusercontent.com/105185/84204858-3ea02180-aaac-11ea-8d8d-129e789c7f52.png)

**Comment by turt2live** [comment]
This has regressed even further as of ~1 week ago. Previously you could "fix" it by sending events or causing the timeline to update, but now it's stuck as broken until you switch rooms.

**Comment by Half-Shot** [comment]
Started to notice that even in 1:1 rooms, the read receipt doesn't move until you click away from the room or the other person sends an event. It's almost as bad as not having them enabled at this point, and it really feels like read receipts being horribly inaccurate should be a :fire: and not a P2.

**Comment by dbkr** [comment]
Looks like this was caused by moving BaseAvatar to hooks in https://github.com/matrix-org/matrix-react-sdk/pull/4101 - it looks like the set if URLs & index are initially defined to be empty / undefined and then subsequently updated, which means BaseAvatar starts out rendering all avatars as the default no-avatar, then updates it to the real avatar immediately afterwards.

This breaks Velocity because it starts out animating the `span` but then this gets swapped out for an `img` just after it starts animating it.

We probably ought to:
 1. Make BaseAvatar be the right avatar from the start rather than changing its mind
 1. Make it handle this more gracefully
 1. Wrap the avatar in a common element so there's a consistent thing to animate

2 & 3 are probably better done by killing off the velocity animations in favour of CSS animations. 1. seems like a thing we ought to do anyway because it must be causing quite a few unnecessary updates every time we re-mount a `BaseAvatar`, but I'm really finding the hook code very hard to read.

**Comment by jryans** [comment]
For part 1 of fixing this, I agree the control flow seems much harder to follow with hooks... 😖 

In more detail, it's not clear to me what a "good" way to compute a complex initial state value before the first render happens, which seems like what we want here to ensure the URL lists are static and unchanging. In a class component, it would be easy to run these steps in the constructor, but I am not sure what the blessed way to do it is for hooks.

**Comment by dbkr** [comment]
Confirmed that above PR fixes the problem with read receipts not moving down, but this bug seems to represent all manner of symptoms so I'm not going to venture to say this issue is fixed.

**Comment by jryans** [comment]
Returning this to the backlog for now, as https://github.com/matrix-org/matrix-react-sdk/pull/5142 seems to address the most critical regression. Future work here would likely endeavour to switch to CSS animations.

**Comment by babolivier** [comment]
I'm still seeing some read receipts not moving down as they should (it's much more rare though), is this expected?

**Comment by jryans** [comment]
> I'm still seeing some read receipts not moving down as they should (it's much more rare though), is this expected?

Yes, that's the known state of the issue at the moment: it should be rare, but still possible.

**Comment by Bubu** [comment]
>  it should be rare

I think it is better than before, but I'd call it far from rare. I'm still seeing it for most of the message for one or two RR avatars in a somewhat busy channel.

Took me about 10 s to wait for an opportunity to grab a screenshot:

![image](https://user-images.githubusercontent.com/105185/91982467-92787a80-ed2a-11ea-9bc8-18c4ce65d893.png)

**Comment by babolivier** [comment]
Agreed, I've been seeing it happen quite reliably for the past few weeks, so it's more frequent than rare atm

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/5697 fixes this. If it doesn't, please open a new issue so we can track symptoms without having to go through a couple years of history.
